### ISSUE TITLE
Link to `popup.html`

### ISSUE THREAD

**Issue by danilbraun** [Own-Data-Privateer/pwebarc#3]
[Here](https://github.com/Own-Data-Privateer/pwebarc/blob/master/extension/page/help.org#how-do-i-properly-archive-a-web-page-completely-especially-when-parts-of-it-are-loaded-lazily) is a link to `popup.html` that doesn't exist.

**Comment by oxij** [comment]
Yes, the top of the file says:

> You can still read this page outside of the extension's UI, but be prepared for all links pointing to =popup.html= to be useless.

**Comment by danilbraun** [comment]
> Yes, the top of the file says:
> […](#)
> You can still read this page outside of the extension's UI, but be prepared for all links pointing to =popup.html= to be useless.

**Comment by oxij** [comment]
It is, however, a valid point that navigating from top-level `README.md` to the "FAQ" will make you miss that warning.
So I added a stub [`popup.html` ](https://github.com/Own-Data-Privateer/pwebarc/blob/master/extension/page/popup.html) to the repo to point the users there.

**Comment by danilbraun** [comment]
> It is, however, a valid point that navigating from top-level `README.md` to the "FAQ" will make you miss that warning. So I added a stub [`popup.html` ](https://github.com/Own-Data-Privateer/pwebarc/blob/master/extension/page/popup.html) to the repo to point the users there.

Yeah, I didn't read that file completely, sorry
